sudo: required
service:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CODE_DISABLE_PROMPTS=1
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project skilful-berm-214822
  - glcoud config set compute/zone us-central-a
  - glcoud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNMAE" --password-stdin
  - docker build -t ashishdlearn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ashishdlearn/react-test npm test -- -- coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
