apiVersion: skaffold/v2beta12
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: ashishdlearn/multi-client
      context: ./client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.css"
            dest: .
          - src: "**/*.html"
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml
